In [1]:
import numpy as np 
import pandas as pd  
from pathlib import Path 

CLEANED_DATAFRAME_LOCATION = Path(r'..\datasets\cleaned_dataset.csv')

cleaned_df = pd.read_csv(CLEANED_DATAFRAME_LOCATION)
cleaned_df.sample(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
1119,1120,US-2021-159184-CHO-FUD-51000,14-09-2024,12-03-2027,Standard Class,159184,United States,Macon,Georgia,31204,Chocolate,Gulf,CHO-FUD-51000,Wonka Bar - Fudge Mallows,7.2,2,4.8,2.4
227,228,US-2021-145317-OTH-FIZ-56000,18-03-2024,13-09-2026,Standard Class,145317,United States,Jacksonville,Florida,32216,Sugar,Gulf,OTH-FIZ-56000,Fizzy Lifting Drinks,15.0,4,9.0,6.0

---
### Profitability Metric Calculation
---
For each product:
- Gross Margin (%)
- Profit per unit
- Total profit contribution

In [2]:
profit_df = cleaned_df.groupby(['Product ID', 'Product Name'])[['Gross Profit', 'Sales', 'Units', 'Cost']].sum().sort_values('Gross Profit', ascending=False)
profit_df['Gross Margin (%)'] = profit_df['Gross Profit'] / profit_df['Sales']
profit_df['profit_per_unit'] = profit_df['Gross Profit'] / profit_df['Units']
profit_df['cost_per_unit'] = profit_df['Cost'] / profit_df['Units']
profit_df['profit_contribution'] = profit_df['Gross Profit'] / sum(profit_df['Gross Profit'])
profit_df['profit_percentage'] = (profit_df['Gross Profit'] / profit_df['Cost'])*100


print('Profitability Metric Calculation by each product')
profit_df.sample(2)

Profitability Metric Calculation by each product

,,Gross Profit,Sales,Units,Cost,Gross Margin (%),profit_per_unit,cost_per_unit,profit_contribution,profit_percentage
Product ID,Product Name,,,,,,,,,
SUG-FUN-75000,Fun Dip,4.8,12.0,8,7.2,0.400000,0.6,0.9,0.000051,66.666667
SUG-SWE-91000,SweeTARTS,28.7,61.5,41,32.8,0.466667,0.7,0.8,0.000307,87.500000

---
### Product Level Profitability Analysis
---
- Rank products by:
    - Gross profit
    - Gross margin
- Identify:
    - High-profit / high-margin products
    - High-sales / low-margin products
    - Low-sales / low-profit products

In [3]:
product_by_top_profit = profit_df.groupby(['Product ID', 'Product Name'])[['Gross Profit']].sum().sort_values('Gross Profit', ascending=False)
product_by_top_margin = profit_df.groupby(['Product ID', 'Product Name'])[['Gross Margin (%)']].sum().sort_values('Gross Margin (%)', ascending=False)

print('-'*70)
print('Top 10 Products by Gross Profit')
print(product_by_top_profit.head(10))
print('-'*70)
print('Top 10 Products by Gross Margin (%)')
print(product_by_top_margin.head(10))

----------------------------------------------------------------------
Top 10 Products by Gross Profit
                                                 Gross Profit
Product ID    Product Name
CHO-SCR-58000 Wonka Bar -Scrumdiddlyumptious         19357.50
CHO-TRI-54000 Wonka Bar - Triple Dazzle Caramel      18610.20
CHO-MIL-31000 Wonka Bar - Milk Chocolate             17443.37
CHO-NUT-13000 Wonka Bar - Nutty Crunch Surprise      16819.95
CHO-FUD-51000 Wonka Bar - Fudge Mallows              16593.60
OTH-LIC-15000 Lickable Wallpaper                      3930.00
OTH-GUM-21000 Wonka Gum                                310.70
SUG-EVE-47000 Everlasting Gobstopper                   104.00
OTH-KAZ-38000 Kazookles                                 92.75
SUG-HAI-55000 Hair Toffee                               59.50
----------------------------------------------------------------------
Top 10 Products by Gross Margin (%)
                                                 Gross Margin (%)
Product ID    Product Name
SUG-EVE-47000 Everlasting Gobstopper                     0.800000
SUG-HAI-55000 Hair Toffee                                0.777778
CHO-NUT-13000 Wonka Bar - Nutty Crunch Surprise          0.713467
CHO-SCR-58000 Wonka Bar -Scrumdiddlyumptious             0.694444
CHO-FUD-51000 Wonka Bar - Fudge Mallows                  0.666667
CHO-TRI-54000 Wonka Bar - Triple Dazzle Caramel          0.653333
CHO-MIL-31000 Wonka Bar - Milk Chocolate                 0.649231
SUG-LAF-25000 Laffy Taffy                                0.623116
OTH-FIZ-56000 Fizzy Lifting Drinks                       0.600000
OTH-GUM-21000 Wonka Gum                                  0.520000

In [4]:
high_profit_high_margin = profit_df[['profit_percentage', 'Gross Margin (%)']].sort_values(by=['profit_percentage', 'Gross Margin (%)'], ascending=[False, False])
high_profit_high_margin.rename(columns={'profit_percentage': 'High Profit', 'Gross Margin (%)': 'High Margin'}, inplace=True)

high_sales_low_margin = profit_df[['Sales', 'Gross Margin (%)']].sort_values(by=['Sales', 'Gross Margin (%)'], ascending=[False, True])
high_sales_low_margin.rename(columns={'Sales': 'High Sales', 'Gross Margin (%)': 'Low Margin'}, inplace=True)

low_sales_low_profit = profit_df[['Sales', 'profit_percentage']].sort_values(by=['Sales', 'profit_percentage'], ascending=[True, True])
low_sales_low_profit.rename(columns={'Sales': 'Low Sales', 'profit_percentage': 'Low Profit'}, inplace=True)

print('_*-'*20)
print('High-Profit / High-Margin Products: ')
print(high_profit_high_margin)
print('_*-'*20)
print('High-Sales / Low-Margin Products: ')
print(high_sales_low_margin)
print('_*-'*20)
print('Low-Sales / Low-Profit Products: ')
print(low_sales_low_profit)

_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-
High-Profit / High-Margin Products:
                                                 High Profit  High Margin
Product ID    Product Name
SUG-EVE-47000 Everlasting Gobstopper              400.000000     0.800000
SUG-HAI-55000 Hair Toffee                         350.000000     0.777778
CHO-NUT-13000 Wonka Bar - Nutty Crunch Surprise   249.000000     0.713467
CHO-SCR-58000 Wonka Bar -Scrumdiddlyumptious      227.272727     0.694444
CHO-FUD-51000 Wonka Bar - Fudge Mallows           200.000000     0.666667
CHO-TRI-54000 Wonka Bar - Triple Dazzle Caramel   188.461538     0.653333
CHO-MIL-31000 Wonka Bar - Milk Chocolate          185.087719     0.649231
SUG-LAF-25000 Laffy Taffy                         165.333333     0.623116
OTH-FIZ-56000 Fizzy Lifting Drinks                150.000000     0.600000
OTH-GUM-21000 Wonka Gum                           108.333333     0.520000
OTH-LIC-15000 Lickable Wallpaper                  100.000000     0.500000
SUG-SWE-91000 SweeTARTS                            87.500000     0.466667
SUG-NER-92000 Nerds                                87.500000     0.466667
SUG-FUN-75000 Fun Dip                              66.666667     0.400000
OTH-KAZ-38000 Kazookles                             8.333333     0.076923
_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-
High-Sales / Low-Margin Products:
                                                 High Sales  Low Margin
Product ID    Product Name
CHO-TRI-54000 Wonka Bar - Triple Dazzle Caramel    28485.00    0.653333
CHO-SCR-58000 Wonka Bar -Scrumdiddlyumptious       27874.80    0.694444
CHO-MIL-31000 Wonka Bar - Milk Chocolate           26867.75    0.649231
CHO-FUD-51000 Wonka Bar - Fudge Mallows            24890.40    0.666667
CHO-NUT-13000 Wonka Bar - Nutty Crunch Surprise    23574.95    0.713467
OTH-LIC-15000 Lickable Wallpaper                    7860.00    0.500000
OTH-KAZ-38000 Kazookles                             1205.75    0.076923
OTH-GUM-21000 Wonka Gum                              597.50    0.520000
SUG-EVE-47000 Everlasting Gobstopper                 130.00    0.800000
OTH-FIZ-56000 Fizzy Lifting Drinks                    78.75    0.600000
SUG-HAI-55000 Hair Toffee                             76.50    0.777778
SUG-SWE-91000 SweeTARTS                               61.50    0.466667
SUG-LAF-25000 Laffy Taffy                             53.73    0.623116
SUG-NER-92000 Nerds                                   15.00    0.466667
SUG-FUN-75000 Fun Dip                                 12.00    0.400000
_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-_*-
Low-Sales / Low-Profit Products:
                                                 Low Sales  Low Profit
Product ID    Product Name
SUG-FUN-75000 Fun Dip                                12.00   66.666667
SUG-NER-92000 Nerds                                  15.00   87.500000
SUG-LAF-25000 Laffy Taffy                            53.73  165.333333
SUG-SWE-91000 SweeTARTS                              61.50   87.500000
SUG-HAI-55000 Hair Toffee                            76.50  350.000000
OTH-FIZ-56000 Fizzy Lifting Drinks                   78.75  150.000000
SUG-EVE-47000 Everlasting Gobstopper                130.00  400.000000
OTH-GUM-21000 Wonka Gum                             597.50  108.333333
OTH-KAZ-38000 Kazookles                            1205.75    8.333333
OTH-LIC-15000 Lickable Wallpaper                   7860.00  100.000000
CHO-NUT-13000 Wonka Bar - Nutty Crunch Surprise   23574.95  249.000000
CHO-FUD-51000 Wonka Bar - Fudge Mallows           24890.40  200.000000
CHO-MIL-31000 Wonka Bar - Milk Chocolate          26867.75  185.087719
CHO-SCR-58000 Wonka Bar -Scrumdiddlyumptious      27874.80  227.272727
CHO-TRI-54000 Wonka Bar - Triple Dazzle Caramel   28485.00  188.461538